.PHONY: deps\:test-ci
deps\:test-ci:
	go install gotest.tools/gotestsum@latest

.PHONY: clean
clean:
	go clean -testcache

.PHONY: test
test:
	@$(MAKE) clean
	cd ./test && go test ./...

.PHONY: test\:memory
test\:memory:
# Environment variable changes do not invalidate the go test cache, so it is important
# for us to clean between each run.
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="memory" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,memory" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="memory,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,memory,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="memory,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,memory,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="memory,txn-multi" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,memory,txn-multi" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="chunk,memory" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,memory" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="memory,chunk,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,memory,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="memory,chunk,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,memory,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="memory,chunk,txn-multi" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,memory,txn-multi" cd ./test && go test ./...

.PHONY: test\:badger
test\:badger:
# Environment variable changes do not invalidate the go test cache, so it is important
# for us to clean between each run.
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="badger" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,badger" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="badger,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,badger,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="badger,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,badger,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="badger,txn-multi" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,badger,txn-multi" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="chunk,badger" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,badger" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="badger,chunk,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,badger,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="badger,chunk,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,badger,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="badger,chunk,txn-multi" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,badger,txn-multi" cd ./test && go test ./...

.PHONY: test\:level
test\:level:
# Environment variable changes do not invalidate the go test cache, so it is important
# for us to clean between each run.
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="level" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,level" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="level,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,level,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="level,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,level,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="level,txn-multi" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,level,txn-multi" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="chunk,level" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,level" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="level,chunk,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,level,txn-commit" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="level,chunk,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,level,txn-discard" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="level,chunk,txn-multi" cd ./test && go test ./...
	@$(MAKE) clean
	CORE_KV_MULTIPLIERS="namespace,chunk,level,txn-multi" cd ./test && go test ./...

.PHONY: test\:all
test\:all:
	@$(MAKE) test:memory
	@$(MAKE) test:badger
	@$(MAKE) test:level

.PHONY: test\:ci
test\:ci:
# We do not make the deps here, the ci does that seperately to avoid compiling stuff
# multiple times etc.
	(cd ./test && gotestsum --format testname ./...)

.PHONY: test\:scripts
test\:scripts:
	@$(MAKE) -C ./tools/scripts/ test

.PHONY: test\:wasm
test\:wasm:
	GOOS=js GOARCH=wasm gotestsum --format testname -- -exec="$(shell go env GOROOT)/lib/wasm/go_js_wasm_exec" ./...

.PHONY: tidy
tidy:
	(cd ./memory && go mod tidy)
	(cd ./namespace && go mod tidy)
	(cd ./badger && go mod tidy)
	(cd ./blockstore && go mod tidy)
	(cd ./chunk && go mod tidy)
	(cd ./level && go mod tidy)
	(cd ./test && go mod tidy)
	go mod tidy
