name: Validate Title Workflow

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  validate-title:
    name: Validate title job

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code into the directory
        uses: actions/checkout@v3

      - name: Ensure the scripts are not broken
        run: make test:scripts

      - name: Run the validation script on the title
        run: ./tools/scripts/validate-conventional-style.sh "${{ github.event.pull_request.title }}"
